#!/bin/bash

# Input_dir=$(cat ~/Destriping_GPU/Destriping_IO_config_MODIS.txt | head -n2 | tail -n1 | tr = ' ' | awk '{print $2}')
# Output_dir=$(cat ~/Destriping_GPU/Destriping_IO_config_MODIS.txt | head -n3 | tail -n1 | tr = ' ' | awk '{print $2}')

paramfile=destriping_modis_param.txt

if [[ $# -ge 2 ]]
then
  Input_dir=$1
  Output_dir=$2
else
  echo "Usage:    $0 Input_striped_dir Output_destriped_dir"
  exit 0
fi

echo "Input_dir = $Input_dir"
echo "Output_dir = $Output_dir"


for f in $Input_dir/M?D021*.hdf
  do 
    if [[ ! -f "$f" ]] 
    then 
      continue
    fi
    fname=$(basename $f)

    isproc=0
    if [[ -f  $Output_dir/Processed_files ]]
    then 
      isproc=$(grep $fname $Output_dir/Processed_files | wc -l)
    fi

    if [ "$isproc" -gt 0 ]
    then
      echo "$Output_dir/$fname   already processed"
    else
#      echo "copy  $f to   $Output_dir/$fname"
      cp -f $f $Output_dir/$fname
      echo "$Output_dir/$fname   destriping"
      ./destripe_modis $Output_dir/$fname $paramfile >> $Output_dir/output_modis.dat
      rc=$?
      if [[ $rc == 0 ]]
      then
        datestring=`date '+%Y%m%d%H%M%S'`
  #     echo "$fname $datestring"
        echo "$fname $datestring" >> $Output_dir/Processed_files
      else
        echo "PROBLEM: $Output_dir/$fname may not be destriped correctly (exit code = $rc) -  will try again next time"
      fi
    fi

done 
