#!/bin/bash

Input_dir_VIIRS=/data/data004/pub/jstroup/VIIRS/aggregation
Output_dir_VIIRS=/data/data036/mikelson/Destriping/VIIRS

Input_dir_Aqua=/data/data079/jstroup/MODIS/Aqua_pm/MOD021KM
Output_dir_Aqua=/data/data036/mikelson/Destriping/MODIS/Aqua_pm/MYD021KM

Input_dir_Terra=/data/data079/jstroup/MODIS/Terra_am/MOD021KM
Output_dir_Terra=/data/data036/mikelson/Destriping/MODIS/Terra_am/MOD021KM

# this variable tells how many days ago from present to keep in destriping buffer
# note that data do not appear immediately in original input buffer, 
# so this needs to be larger than anticipated size of output buffer
maxdaysago_VIIRS=30
maxdaysago_Aqua=30
maxdaysago_Terra=30

# make sure we always have only at most one instance of this script running
# NOTE: ./destriping_is_running is a lock file which exists while this script is running;
#       If this script gets killed, ./destriping_is_running must be deleted before
#       this script can be run again
cd ~/scripts_rotational_buffer_v2/
if [ -f ./destriping_is_running ]; then
  echo "destriping is already running"
  echo "exiting script"
  exit 0
fi
touch ./destriping_is_running

# export default number of threads to use by destriping
export OMP_NUM_THREADS=8

#####################################################################################
### DESTRIPE VIIRS DATA   ###########################################################
#####################################################################################

if [[ ! -d "$Input_dir_VIIRS" ]]
then
  echo "Input path $Input_dir_VIIRS does not exist" 
  exit -1
fi

if [[ ! -d "$Output_dir_VIIRS" ]]
then
  echo "Output path $Output_dir_VIIRS does not exist" 
  exit -1
fi

echo "Input_dir_VIIRS = $Input_dir_VIIRS"
echo "Output_dir_VIIRS = $Output_dir_VIIRS"


for ((daysago=0;daysago<=maxdaysago_VIIRS;daysago++)); do
  datestr=$(date  --date="$daysago days ago" '+%Y%m%d')
#  echo $datestr
  Indir="$Input_dir_VIIRS/$datestr"
  Outdir="$Output_dir_VIIRS/$datestr"
#  echo $Indir
#  echo $Outdir

  if [[ -d "$Indir" ]] 
  then
    echo "$Indir  - destriping input"
    if [[ ! -d "$Outdir" ]] 
    then
#      echo "mkdir $Outdir"
      mkdir $Outdir
      if [[ ! -d "$Outdir" ]]
      then 
        echo "Cannot create outpt directory $Outdir - skipping"
        continue
      fi
    else 
      echo "$Outdir already exists"
    fi
    # run detriping here
    ./destripe_dir_viirs $Indir $Outdir 
  else
    echo "$Indir does not exist - skipping"
  fi
done


# cycle through all directories in output path
# and see which ones should be kept
# and delete the ones that should not
for f in $Output_dir_VIIRS/*
do
  # extract subdirectory name = date label
  daylabel=$(echo $f | tr  / ' ' | awk '{print $NF}')
  # determine if it is equal to any of the recent directories that should be kept
  keepthisdir=0
  for ((daysago=0;daysago<=maxdaysago_VIIRS;daysago++)); do
    datestr=$(date  --date="$daysago days ago" '+%Y%m%d')
    if [[ "$datestr" == "$daylabel" ]] 
    then
      keepthisdir=1
    fi
  done
  # delete if should not be kept
  if [[ $keepthisdir -eq 0 ]] 
  then
    echo "Removing $f"
    rm -rf $f
  else 
    echo "Keeping  $f"
  fi
done



#####################################################################################
### DO ALL THE SAME FOR MODIS Aqua  #################################################
#####################################################################################

if [[ ! -d "$Input_dir_Aqua" ]]
then
  echo "Input path $Input_dir_Aqua does not exist" 
  exit -1
fi

if [[ ! -d "$Output_dir_Aqua" ]]
then
  echo "Output path $Output_dir_Aqua does not exist" 
  exit -1
fi

echo "Input_dir_Aqua = $Input_dir_Aqua"
echo "Output_dir_Aqua = $Output_dir_Aqua"


for ((daysago=0;daysago<=maxdaysago_Aqua;daysago++)); do
  datestr=$(date  --date="$daysago days ago" '+%j')
#  echo $datestr
  Indir="$Input_dir_Aqua/$datestr"
  Outdir="$Output_dir_Aqua/$datestr"
#  echo $Indir
#  echo $Outdir

  if [[ -d "$Indir" ]] 
  then
    echo "$Indir  - destriping input"
    if [[ ! -d "$Outdir" ]] 
    then
#      echo "mkdir $Outdir"
      mkdir $Outdir
      if [[ ! -d "$Outdir" ]]
      then 
        echo "Cannot create outpt directory $Outdir - skipping"
        continue
      fi
    else 
      echo "$Outdir already exists"
    fi
    # run detriping here
    ./destripe_dir_modis $Indir $Outdir 
  else
    echo "$Indir does not exist - skipping"
  fi
done


# cycle through all directories in output path
# and see which ones should be kept
# and delete the ones that should not
for f in $Output_dir_Aqua/*
do
  # extract subdirectory name = date label
  daylabel=$(echo $f | tr  / ' ' | awk '{print $NF}')
  # determine if it is equal to any of the recent directories that should be kept
  keepthisdir=0
  for ((daysago=0;daysago<=maxdaysago_Aqua;daysago++)); do
    datestr=$(date  --date="$daysago days ago" '+%j')
    if [[ "$datestr" == "$daylabel" ]]
    then
      keepthisdir=1
    fi
  done
  # delete if should not be kept
  if [[ $keepthisdir -eq 0 ]] 
  then
    echo "Removing $f"
    rm -rf $f
  else 
    echo "Keeping  $f"
  fi
done


#####################################################################################
### DO ALL THE SAME FOR MODIS Terra #################################################
#####################################################################################

if [[ ! -d "$Input_dir_Terra" ]]
then
  echo "Input path $Input_dir_Terra does not exist" 
  exit -1
fi

if [[ ! -d "$Output_dir_Terra" ]]
then
  echo "Output path $Output_dir_Terra does not exist" 
  exit -1
fi

echo "Input_dir_Terra = $Input_dir_Terra"
echo "Output_dir_Terra = $Output_dir_Terra"


for ((daysago=0;daysago<=maxdaysago_Terra;daysago++)); do
  datestr=$(date  --date="$daysago days ago" '+%j')
#  echo $datestr
  Indir="$Input_dir_Terra/$datestr"
  Outdir="$Output_dir_Terra/$datestr"
#  echo $Indir
#  echo $Outdir

  if [[ -d "$Indir" ]] 
  then
    echo "$Indir  - destriping input"
    if [[ ! -d "$Outdir" ]] 
    then
#      echo "mkdir $Outdir"
      mkdir $Outdir
      if [[ ! -d "$Outdir" ]]
      then 
        echo "Cannot create outpt directory $Outdir - skipping"
        continue
      fi
    else 
      echo "$Outdir already exists"
    fi
    # run detriping here
    ./destripe_dir_modis $Indir $Outdir 
  else
    echo "$Indir does not exist - skipping"
  fi
done


# cycle through all directories in output path
# and see which ones should be kept
# and delete the ones that should not
for f in $Output_dir_Terra/*
do
  # extract subdirectory name = date label
  daylabel=$(echo $f | tr  / ' ' | awk '{print $NF}')
  # determine if it is equal to any of the recent directories that should be kept
  keepthisdir=0
  for ((daysago=0;daysago<=maxdaysago_Terra;daysago++)); do
    datestr=$(date  --date="$daysago days ago" '+%j')
    if [[ "$datestr" == "$daylabel" ]] 
    then
      keepthisdir=1
    fi
  done
  # delete if should not be kept
  if [[ $keepthisdir -eq 0 ]] 
  then
    echo "Removing $f"
    rm -rf $f
  else 
    echo "Keeping  $f"
  fi
done


rm ./destriping_is_running

